name: Build GH-Pages

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'LICENSE'
      - 'README.md'
    branches:
      - main
  workflow_dispatch:
    # manual run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Submodule Add PaperMod
        run: git submodule add https://github.com/adityatelange/hugo-PaperMod.git themes/hugo-PaperMod
        
        # Must be sure 8~12 is powering list
      - name: Remove Powering list
        run: |
          vim /home/runner/work/zhiweitong.github.io/zhiweitong.github.io/themes/hugo-PaperMod/layouts/partials/footer.html << EOF
          : 8, 12d
          :wq
          EOF

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --buildDrafts --gc --verbose --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
